### ISSUE TITLE
Add Staff to Vendor P2

### ISSUE THREAD

**Issue by gwynnemeeks** [nss-evening-cohort-12/nutshell-muntjac#104]
# User Story
As a user, I should be able to assign a Staff member to a Vendor (#77 )
---
As a user when signed in I should be able to visit the staff member page and see a list of staff members. There should be a button that allows adding a staff member to a vendor(#92 ). When the button is clicked a form should appear with radio buttons for each Staff Member. Choosing a radio button and clicking the submit button will add the staff member to the vendor card.

# AC
---
**Then** the user should be able to click and select a certain vendor they wish the staff member to work and submit it.
**When** submitted it should apply that staff member to that vendor card, updating the vendor to show who is working it.

# ToDo
---
- [x] Issue #92  must be complete before starting
- [x] Create a smash function that will fetch each staffId and each vendorId
- [x] Use the smash function in a function designed to update a staff member to accept a vendorId and assigns them to that vendor
- [x] Add on to the vendor card a line that displays which staff member is working that vendor
