### ISSUE TITLE
Create a Tracker for total money spent on visitorLog

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-muntjac#120]
### **User Story**
---
As a user when i visit the visitors page i should see a list of users with a button that says visitor activity. When i click and open the visitor activity log ( #97 ) i should see a list of all activities with the visitors name the activity name and the activity cost. at the top there should be a static line that keeps track of all money spent in the park up to that moment.

### **AC**
---
**When** the user goes to the visitor page and opens the log they should see a list of visitors with the activities they are doing or have done and there prices
**Then** at the top they should see a header type line that says total money spent at the park
**Finally** a running total should be kept and should update when the log updates with new activities

### **To Do**
---
- [x] Create a new function that loops through the visitorLog data ( #105 )
- [x] Create a function that pushes just the cost/prices of the activities done from the log into an array
- [x] Create a function that adds all prices/costs inside the array into one some
- [x] Create a function that prints the total to the log ( #107 )
