### ISSUE TITLE
Staff

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/nutshell-muntjac#3]
# User Stories
- [x] As a user, I should be able to view all Staff.
- [x] As a user, I should be able to add Staff. (#23 )
- [x] As a user, I should be able to edit Staff. (#26 )
- [x] As a user, I should be able to remove Staff. (#27 )

**Comment by TheDotson** [comment]
Example for Staff database 
`{
	"employee01": {
		"employeeId": "00001",
		"firstName": "Jeff",
		"lastName": "Bridges",
		"position": "Dude"
	}
}
`
