### ISSUE TITLE
Visitor Activity and Spending Tracker

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-muntjac#97]
### **User Story**
---
As a user when i visit the visitors page i should see a list of visitors and at the top of the page a button with a clipboard icon stating activity log. when the button is clicked a div/box should populate below all the visitors and display all activity from all visitors that has occurred up to that point ( #107  ). The Visitors name should be printed along with the activity and the money it cost to purchase said activity. When something new is bought ( #95 ) the new activity each visitor bought should update in the data file ( #105 ) and print to the tracker div ( #107  )

### **AC**
---
**When** the user visits the visitor page they should see a list of visitors and a button at the top called activity log
**When** the user clicks the activity log button a div/box should appear at the bottom of the page. ( #107 )
**Then** the user should see a list of all purchases and activities made by all visitors. the visitors name should be to the left of it.
**When** the buy button is clicked and all visitors buy something new the new activity should print to the log with the visitor who bought it and the money it cose

### **To Do**
--- 

- [x] Create a new component call visitorTracker
- [x] Create a new js file called visitorTracker
- [x] Create a clipboard button that populates at the bottom of every student card and attach a listener event to them that populates a div
- [x] Create a get request that gets the data from the activityLog data and builds a small string and prints it to the dom(it should have the visitors name, the money spent, and what the activity was)

**Comment by luketlancaster** [comment]
what kind of axios requests do you see yourself needing for this? Will you need to add some database rules?

**Comment by medlenmage** [comment]
will most likely have to do an axios get for the specific data from visitors data so axios.get with an argument for whatever the property would be named such as activity or expenditure/

rules i think i'll have to do a .indexOn rule which i guess i need to update this card with that information thanks for the call outs on it!

**Comment by medlenmage** [comment]
@luketlancaster does this look better?

**Comment by luketlancaster** [comment]
so this information is going to go on your visitor table? So each visitor will only ever have one kind of activity?

**Comment by medlenmage** [comment]
it all should print to and stay in a running log for each persons activity on a single board(sort of like the chatty excessive).

i'll re-write the top part of the card.

**Comment by luketlancaster** [comment]
so this means you'll need a visitorLog table right? So you won't be doing a GET request to the visitor table, but to the visitorLog table?

**Comment by medlenmage** [comment]
oh ok so you mean like i should have a data file or whatever that pushes the visitor activity to it then GET the data from there to push to the log?

**Comment by luketlancaster** [comment]
yeah, the new db table (which I'm calling visitorLog here, you can call it whatever you want) is where you'll store every thing a visitor has done, each "purchase" they've made. So that's what you'll get from, and you'll need to figure out what that log looks like/what properties are on it if you haven't already. 

You need to do this because a visitor can have > 1 thing they've purchased right? In fact they can have as many as they like. So you need a join table to determine what things they've bought

**Comment by medlenmage** [comment]
gotcha. that makes sense thank you for direction.

**Comment by medlenmage** [comment]
ok i think i got this card squared away finally does this seem right?

**Comment by luketlancaster** [comment]
I'd break this up into a couple of cards. Creating the initial data could be one, doing the display of visitor activity, maybe linking to the card where you'll add visitor activity and how this new table will be implemented, etc

**Comment by medlenmage** [comment]
makes sense i'll get to that
